/* de265-version.h
 *
 * This file was generated by autoconf when libde265 was built.
 *
 * DO NOT EDIT THIS FILE.
 */
#ifndef LIBDE265_VERSION_H
#define LIBDE265_VERSION_H

/* Numeric representation of the version */
#define LIBDE265_NUMERIC_VERSION 0x00060000

#define LIBDE265_VERSION "0.6"

#endif
