/* de265-config.h
 *
 * This file was generated by autoconf when libde265 was built, and post-
 * processed by libde265 so that its macros would have a uniform prefix.
 *
 * DO NOT EDIT THIS FILE.
 *
 * Do not rely on macros in this file existing in later versions.
 */
#ifndef _LIBDE265_CONFIG_H_
#define _LIBDE265_CONFIG_H_
/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define _LIBDE265_HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define _LIBDE265_HAVE_INTTYPES_H 1

/* Define to 1 if you have the `malloc' function. */
#define _LIBDE265_HAVE_MALLOC 1

/* Define to 1 if you have the <malloc.h> header file. */
#define _LIBDE265_HAVE_MALLOC_H 1

/* Define to 1 if you have the `memalign' function. */
#define _LIBDE265_HAVE_MEMALIGN 1

/* Define to 1 if you have the `memmove' function. */
#define _LIBDE265_HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define _LIBDE265_HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define _LIBDE265_HAVE_MEMSET 1

/* Define to 1 if you have the `posix_memalign' function. */
#define _LIBDE265_HAVE_POSIX_MEMALIGN 1

/* Whether libSDL was found. */
#define _LIBDE265_HAVE_SDL 1

/* Support SSSE4.1 (Streaming SIMD Extensions 4.1) instructions */
#define _LIBDE265_HAVE_SSE4_1 1

/* Define to 1 if stdbool.h conforms to C99. */
#define _LIBDE265_HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define _LIBDE265_HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define _LIBDE265_HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define _LIBDE265_HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define _LIBDE265_HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define _LIBDE265_HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define _LIBDE265_HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define _LIBDE265_HAVE_UNISTD_H 1

/* Whether libvideogfx was found. */
/* #undef _LIBDE265_HAVE_VIDEOGFX */

/* Define to 1 if the system has the type `_Bool'. */
#define _LIBDE265_HAVE__BOOL 1

/* Define to 1 if you have the `__malloc_hook' function. */
#define _LIBDE265_HAVE___MALLOC_HOOK 1

/* Define to 1 if you have the `__mingw_aligned_free' function. */
/* #undef _LIBDE265_HAVE___MINGW_ALIGNED_FREE */

/* Define to 1 if you have the `__mingw_aligned_malloc' function. */
/* #undef _LIBDE265_HAVE___MINGW_ALIGNED_MALLOC */

/* Define to the sub-directory in which libtool stores uninstalled libraries.
   */
#define _LIBDE265_LT_OBJDIR ".libs/"

/* Numeric representation of the version */
#define _LIBDE265_NUMERIC_VERSION 0x00040000

/* Name of package */
#define _LIBDE265_PACKAGE "libde265"

/* Define to the address where bug reports for this package should be sent. */
#define _LIBDE265_PACKAGE_BUGREPORT "farin@struktur.de"

/* Define to the full name of this package. */
#define _LIBDE265_PACKAGE_NAME "libde265"

/* Define to the full name and version of this package. */
#define _LIBDE265_PACKAGE_STRING "libde265 0.4"

/* Define to the one symbol short name of this package. */
#define _LIBDE265_PACKAGE_TARNAME "libde265"

/* Define to the home page for this package. */
#define _LIBDE265_PACKAGE_URL ""

/* Define to the version of this package. */
#define _LIBDE265_PACKAGE_VERSION "0.4"

/* Define to 1 if you have the ANSI C header files. */
#define _LIBDE265_STDC_HEADERS 1

/* Version number of package */
#define _LIBDE265_VERSION "0.4"

/* Define for Solaris 2.5.1 so the uint32_t typedef from <sys/synch.h>,
   <pthread.h>, or <semaphore.h> is not used. If the typedef were allowed, the
   #define _LIBDE265_below would cause a syntax error. */
/* #undef _LIBDE265__UINT32_T */

/* Define for Solaris 2.5.1 so the uint64_t typedef from <sys/synch.h>,
   <pthread.h>, or <semaphore.h> is not used. If the typedef were allowed, the
   #define _LIBDE265_below would cause a syntax error. */
/* #undef _LIBDE265__UINT64_T */

/* Define for Solaris 2.5.1 so the uint8_t typedef from <sys/synch.h>,
   <pthread.h>, or <semaphore.h> is not used. If the typedef were allowed, the
   #define _LIBDE265_below would cause a syntax error. */
/* #undef _LIBDE265__UINT8_T */

/* Define to the type of a signed integer type of width exactly 16 bits if
   such a type exists and the standard includes do not define it. */
/* #undef _LIBDE265_int16_t */

/* Define to the type of a signed integer type of width exactly 32 bits if
   such a type exists and the standard includes do not define it. */
/* #undef _LIBDE265_int32_t */

/* Define to the type of a signed integer type of width exactly 8 bits if such
   a type exists and the standard includes do not define it. */
/* #undef _LIBDE265_int8_t */

/* Define to the type of an unsigned integer type of width exactly 16 bits if
   such a type exists and the standard includes do not define it. */
/* #undef _LIBDE265_uint16_t */

/* Define to the type of an unsigned integer type of width exactly 32 bits if
   such a type exists and the standard includes do not define it. */
/* #undef _LIBDE265_uint32_t */

/* Define to the type of an unsigned integer type of width exactly 64 bits if
   such a type exists and the standard includes do not define it. */
/* #undef _LIBDE265_uint64_t */

/* Define to the type of an unsigned integer type of width exactly 8 bits if
   such a type exists and the standard includes do not define it. */
/* #undef _LIBDE265_uint8_t */
#endif
