
SRCS=sse.cc ../libde265/fallback-sao.cc ../libde265/x86/sse-sao.cc ../libde265/x86/sse-dct.cc \
  ../libde265/fallback-intra-dc.cc ../libde265/x86/sse-intra-dc.cc \
  ../libde265/fallback-dct.cc \
  intra-dc.cc motion.cc dct.cc

INTELPATH=$(HOME)/src/IntelPerformanceCounterMonitor-V2.11
INTELSRCS=msr.cpp cpucounters.cpp pci.cpp client_bw.cpp utils.cpp
INTELSRC=
# $(INTELSRCS:%.cpp=$(INTELPATH)/%.cpp)

OBJS=$(SRCS:.cc=.o)

IACAPATH=$(HOME)/opt/iaca-lin64/include

sse: $(SRCS) $(INTELSRC)
	g++ -std=c++11 $(SRCS) $(INTELSRC) -DHAVE_SSE4_1 -I.. -I../libde265 -I$(INTELPATH) -I$(IACAPATH) -O3 -g -msse4 -o sse -lpthread -lrt

clean:
	rm sse
