
SRCS=sse.cc ../libde265/fallback-sao.cc ../libde265/x86/sse-sao.cc \
  ../libde265/fallback-intra-dc.cc ../libde265/x86/sse-intra-dc.cc \
  intra-dc.cc
OBJS=$(SRCS:.cc=.o)

sse: $(SRCS)
	g++ $(SRCS) -I.. -I../libde265 -O3 -g -msse4 -o sse

clean:
	rm sse
