name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        env:
          - { CC: "gcc", CXX: "g++" }
          - { CC: "clang", CXX: "clang++" }
          - { CMAKE: "cmake" }
    env: ${{ matrix.env }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5

    - name: Checkout sample streams
      uses: actions/checkout@v5
      with:
        repository: strukturag/libde265-data
        path: libde265-data

    - name: Install dependencies
      run: |
        ./scripts/ci-before-install-linux.sh

    - name: Prepare CI
      run: |
        ./scripts/ci-before-script.sh

    - name: Run tests
      run: |
        ./scripts/ci-run.sh
