name: lint

on: [push, pull_request]

jobs:
  licensecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

    - name: Install dependencies
      run: |
        sudo apt install -qq licensecheck

    - name: Check licenses
      run: |
        ./scripts/check_licenses.sh
