name: lint

on: [push, pull_request]

jobs:
  licensecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

    - name: Install dependencies
      run: |
        sudo apt install -qq licensecheck

    - name: Check licenses
      run: |
        ./scripts/check_licenses.sh
