name: osx

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, macos-15]
        env:
          - { CC: "clang", CXX: "clang++" }
          - { CC: "gcc", CXX: "g++" }
    env: ${{ matrix.env }}

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

    - name: Checkout sample streams
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      with:
        repository: strukturag/libde265-data
        path: libde265-data

    - name: Install dependencies
      run: |
        ./scripts/ci-before-install-osx.sh

    - name: Prepare CI
      run: |
        ./scripts/ci-before-script.sh

    - name: Run tests
      run: |
        ./scripts/ci-run.sh
